import { Client } from '@notionhq/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Todo from './todo'

interface Props {
  results: any;
}
// const notion = new Client({auth: process.env.NOTION_TOKEN});
const Home: NextPage<Props> = ({results}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Todo/>
      </main>
    </div>
  )
}

export default Home

// export async function getServerSideProps() {
//   const results = await notion.databases.query({
//     database_id: `${process.env.NOTION_DATABASE_ID}`,
//   });
//   return {
//       props: {
//         results
//       }
//   }
// }
