import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Todo from './todo'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Test To Do List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Todo/>
      </main>
    </div>
  )
}

export default Home
